name: epi2melabs-nf-human-snp
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - aplanat
    - bcftools
    - clair3==0.1.8
    - fastcat>=0.4.8
    - epi2melabs